### ISSUE TITLE
Error:cannot import name 'PositionNet' from 'diffusers.models.embeddings'

### ISSUE THREAD

**Issue by ultimatech-cn** [chaojie/ComfyUI-Moore-AnimateAnyone#14]
After restarting ComfyUI, the node import failed, which used to be fine.
`
Cannot import E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Moore-AnimateAnyone module for custom nodes: cannot import name 'PositionNet' from 'diffusers.models.embeddings' (E:\DEV\ComfyUI_windows_portable\python_embeded\lib\site-packages\diffusers\models\embeddings.py)`

Any solution for that? Update or downgrade diffusers?

**Comment by kesyn** [comment]
Same here, downgrade to 0.24.0 solves this.

**Comment by ultimatech-cn** [comment]
Nice. I have already give it up.
