### ISSUE TITLE
ComfyUI-Moore-AnimateAnyone module for custom nodes: cannot import name 'CaptionProjection' from 'diffusers.models.embeddings' (C:\Users\xxx\.conda\envs\SD-use\lib\site-packages\diffusers\models\embeddings.py)

### ISSUE THREAD

**Issue by HandsomeDong** [chaojie/ComfyUI-Moore-AnimateAnyone#4]
After successfully git clone && install && run download_weights, I got this error when I start ComfyUI
![QQ截图20240119210050](https://github.com/chaojie/ComfyUI-Moore-AnimateAnyone/assets/49794748/9e0abd8d-a587-4bb4-8d0f-b009be7a15e7)

![QQ截图20240119210103](https://github.com/chaojie/ComfyUI-Moore-AnimateAnyone/assets/49794748/4b2cd807-4b08-4076-b756-0821a7039cf5)

**Comment by chaojie** [comment]
https://github.com/MooreThreads/Moore-AnimateAnyone/issues/13

You have this error because you are using newest diffusers library

To fix, in transformer_2d.py:

Replace CaptionProjection with PixArtAlphaTextProjection

**Comment by HandsomeDong** [comment]
> CaptionProjection

Thanks! Resolved it!

**Comment by HandsomeDong** [comment]
> [MooreThreads/Moore-AnimateAnyone#13](https://github.com/MooreThreads/Moore-AnimateAnyone/issues/13)
> 
> You have this error because you are using newest diffusers library
> 
> To fix, in transformer_2d.py:
> 
> Replace CaptionProjection with PixArtAlphaTextProjection
Thanks! Resolved it!

**Comment by HandsomeDong** [comment]
> [MooreThreads/Moore-AnimateAnyone#13](https://github.com/MooreThreads/Moore-AnimateAnyone/issues/13)
> 
> You have this error because you are using newest diffusers library
> 
> To fix, in transformer_2d.py:
> 
> Replace CaptionProjection with PixArtAlphaTextProjection


Thanks! Resolved it!
